version: '2.3'

services:
  ucsl:
    container_name: ucsl-container
    build:
      context: .
      args:
        NB_USER: ${NB_USER}
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./notebooks
        target: /home/${NB_USER}/puinotebooks/
